[env:controllino_maxi]
platform = atmelavr
board = controllino_maxi
framework = arduino
monitor_speed = 115200

lib_deps =
    Elementic@^1.0.0
    arduino-libraries/Ethernet
    knolleary/PubSubClient@^2.8
