[env:controllino_maxi]
platform = atmelavr
board = controllino_maxi
framework = arduino
monitor_speed = 115200

lib_extra_dirs = ../../..

lib_deps =
    arduino-libraries/Ethernet
    knolleary/PubSubClient@^2.8
