[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
build_flags = -DUSE_WIFI
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    rsauer/Elementic@^1.0.0
    knolleary/PubSubClient@^2.8
